- hosts: Ubuntu_login
  become: yes
  tasks:

  - name: Install soft
    apt:
      name: "{{ item }}"
      state: latest 
    with_items:
           - python3
           - apache2
           - nodejs
           - npm
           - nodejs-legacy
           - libpq-dev

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: npm config set strict-ssl false

  - name: Install needed modules
    shell: npm install express cors body-parser pg nave

  - name: Creating index
    copy:
       src: /etc/ansible/login_page/index.html
       dest: /var/www/html

  - name: JS code
    copy:
       src: /etc/ansible/login_page/login_js.js
       dest: /home/vmadmin/node_modules

  - name: Update apache2
    service:
       name: apache2
       state: restarted
       enabled: yes
