---
- hosts: Centos
  become: yes

  pre_tasks:
    - name: "Install packages"
      yum: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server
        - epel-release
        - python-pip
        - python3-devel
        - postgresql-libs
        - postgresql-devel
        - python-psycopg2

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Create app database"
      postgresql_db:
        state: present
        name: datab
      become: yes
      become_user: postgres

    - name: Ensure db table for temp is present
      become: true
      become_user: postgres
      postgresql_table:
        db: datab
        table: use
        columns:
           - name VARCHAR(255)
           - email VARCHAR(255)
           - pwd VARCHAR(255)

    - name: Set ip address for postgresql
      copy:
          src: /etc/ansible/postgresql/postgresql.conf
          dest: /var/lib/pgsql/data
    
    - name: Set ip address for postgresql
      copy:
          src: /etc/ansible/postgresql/pg_hba.conf
          dest: /var/lib/pgsql/data

    - name: pd reset database user
      become: yes
      become_user: postgres
      postgresql_user: 
        db: datab
        name: postgres
        password: "1a34"
    - name: restart postgresql 
      service: name=postgresql state=restarted 
  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
